# Generated by Django 6.0.3 on 2026-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='est_archivee',
            field=models.BooleanField(default=False),
        ),
    ]
