"""
Django settings for orientation project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7tfjf1ubruwpnz80j+%14$m%)n%*x2fra1a&+tlevr*6piu3d9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'comptes',
    'interactions',
    'cloudinary_storage',
    'cloudinary',
]
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Ajout du middleware pour servir les fichiers statiques en production
]

ROOT_URLCONF = 'orientation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'interactions.compteur.notifications_count', # Ajout du context processor pour les notifications    
            ],
        },
    },
]

WSGI_APPLICATION = 'orientation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url
import os

# Configuration de la base de données
DATABASES = {
    'default': dj_database_url.config(
        # Sur ton PC, il utilisera SQLite. Sur Railway, il utilisera DATABASE_URL (Postgres)
        default=f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}",
        conn_max_age=600
    )
}

# Cette partie est cruciale pour Railway/Postgres
if 'DATABASE_URL' in os.environ:
    DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}
else:
    # On retire sslmode si on est en local sur SQLite pour éviter ton erreur
    DATABASES['default'].pop('OPTIONS', None)

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Dossier physique où vous rangez vos fichiers (CSS, JS, images de design)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Dossier où Django rassemblera tous les statiques lors de la mise en ligne (Déploiement)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Après la connexion, on va vers l'accueil (nom de l'url 'home')
LOGIN_REDIRECT_URL = 'home'

# Après la déconnexion, on revient aussi à l'accueil

LOGOUT_REDIRECT_URL = 'home'

# Pour le développement (affiche le mail dans le terminal)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Plus tard, pour la mise en ligne, on utilisera Gmail ou SendGrid :
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# ... etc

# Nom qui apparaîtra dans l'objet et la signature du mail
DEFAULT_FROM_EMAIL = 'ORIENTATION STIM <noreply@orientationstim.bj>'
CSRF_TRUSTED_ORIGINS = ['https://web-production-981a.up.railway.app']