# Generated by Django 6.0.3 on 2026-03-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_detaille', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ecoles/logos/')),
                ('description', models.TextField()),
                ('map_iframe', models.TextField(blank=True, help_text="Collez ici le code 'Intégrer une carte' de Google Maps", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('nom_complet', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(upload_to='universites/logos/')),
                ('description', models.TextField()),
                ('localisation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('debouches', models.TextField()),
                ('bourses', models.TextField(blank=True, help_text='Détails sur les bourses disponibles', null=True)),
                ('aides_universitaires', models.TextField(blank=True, help_text='Détails sur les aides universitaires disponibles', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ManyToManyField(related_name='filieres', to='blog.admission')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='blog.ecole')),
                ('matieres_principales', models.ManyToManyField(related_name='filieres', to='blog.matiere')),
                ('series_autorisees', models.ManyToManyField(related_name='filieres', to='blog.serie')),
            ],
        ),
        migrations.AddField(
            model_name='ecole',
            name='universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecoles', to='blog.universite'),
        ),
    ]
