# Generated by Django 6.0.3 on 2026-03-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_universite_localisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='description',
        ),
    ]
