# Generated by Django 6.0.3 on 2026-03-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_filiere_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecole',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['nom'], 'verbose_name': 'Filière'},
        ),
        migrations.AlterModelOptions(
            name='universite',
            options={'ordering': ['nom'], 'verbose_name': 'Université'},
        ),
        migrations.RenameField(
            model_name='ecole',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='filiere',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
