# Generated by Django 6.0.3 on 2026-04-04 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_ecole_options_alter_filiere_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('variantes', models.ManyToManyField(blank=True, help_text='Sélectionnez toutes les matières qui correspondent à cette discipline', related_name='disciplines_parentes', to='blog.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='CoefficientSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.PositiveIntegerField(help_text='Le coefficient officiel au Bénin pour cette série')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='blog.serie')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='blog.discipline')),
            ],
            options={
                'verbose_name': 'Coefficient par Série',
                'unique_together': {('discipline', 'serie')},
            },
        ),
    ]
