# Generated by Django 6.0.3 on 2026-04-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_discipline_coefficientserie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='variantes',
        ),
        migrations.AddField(
            model_name='matiere',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes', to='blog.discipline'),
        ),
    ]
