# Generated by Django 6.0.3 on 2026-04-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_discipline_variantes_matiere_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='discipline',
        ),
        migrations.CreateModel(
            name='RegleAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='blog.filiere')),
                ('matieres_poids', models.ManyToManyField(help_text='Les matières mères comptant pour cette série dans cette filière', to='blog.discipline')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.serie')),
            ],
            options={
                'verbose_name': "Règle d'admission",
                'unique_together': {('filiere', 'serie')},
            },
        ),
    ]
