# Generated by Django 6.0.3 on 2026-04-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_commentaire_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
