data= [
    {
        "univ": "UP",
        "ecole": "FA",
        "nom_complet": "Faculté d'Agronomie",
        "nom": "Sciences et Techniques de Production Végétale",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/(toutes options)"],
        "matieres": ["Maths (C, D)", "SPCT (C, D)", "SVT (C, D)", "Toutes les trois (03) matières écrites (DEAT)"],
        "bourses": "22",
        "aides": "0",
        "debouches": "Entrepreneur Agricole\nConseiller Agricole\nTechnicien/Encadreur en production végétale\nprotection des végétaux\nsélection variétale\ngestion durable des terres\nEnseignant des lycées agricoles"
    },
    {
        "univ": "UP",
        "ecole": "FA",
        "nom_complet": "Faculté d'Agronomie",
        "nom": "Sciences et Techniques de Production Animale et Halieutique",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/(toutes options)"],
        "matieres": ["Maths (C, D)", "SPCT (C, D)", "SVT (C, D)", "Toutes les trois (03) matières écrites (DEAT)"],
        "bourses": "21",
        "aides": "0",
        "debouches": "Technicien en gestion et conduite d'élevage\nGestion des exploitations animales et aquacoles\nEntrepreneur Agricole\nConseiller Agricole\nEnseignant des lycées agricoles"
    },
    {
        "univ": "UP",
        "ecole": "FA",
        "nom_complet": "Faculté d'Agronomie",
        "nom": "Aménagement et Gestion des Ressources Naturelles",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/(toutes options)"],
        "matieres": ["Maths (C, D)", "SPCT (C, D)", "SVT (C, D)", "Toutes les trois (03) matières écrites (DEAT)"],
        "bourses": "20",
        "aides": "0",
        "debouches": "Technicien en aménagement et gestion des aires protégées\nCadre des eaux et forêts\nAssistance dans les études de gestion et de conservation des aires protégées\nEntrepreneur Agricole\nConseiller Agricole\nEnseignant des lycées agricoles"
    },
    {
        "univ": "UP",
        "ecole": "FA",
        "nom_complet": "Faculté d'Agronomie",
        "nom": "Sociologie et Economie Rurales",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/(toutes options)"],
        "matieres": ["Maths (C, D)", "SPCT (C, D)", "SVT (C, D)", "Toutes les trois (03) matières écrites (DEAT)"],
        "bourses": "22",
        "aides": "0",
        "debouches": "Assistance dans la création et la gestion d'entreprise/coopérative agricole\nMise en place et gestion de cluster agricole\nAppui conseil au développement local\nFacilitation de la mise en place des innovations institutionnelles\nAssistance dans les études socio-économiques"
    },
    {
        "univ": "UP",
        "ecole": "FA",
        "nom_complet": "Faculté d'Agronomie",
        "nom": "Nutrition et Sciences Agroalimentaires",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/(toutes options)"],
        "matieres": ["Maths (C, D)", "SPCT (C, D)", "SVT (C, D)", "Toutes les trois (03) matières écrites (DEAT)"],
        "bourses": "20",
        "aides": "0",
        "debouches": "Entrepreneur Agro-alimentaire\nResponsable système de qualité IAA\nChef production IAA\nTechnicien en nutrition et sciences agroalimentaires\nEnseignant des lycées agricoles"
    },
    {
        "univ": "UP",
        "ecole": "FM",
        "nom_complet": "Faculté de Médecine",
        "nom": "Médecine Humaine",
        "mode": "Classement",
        "series": ["C", "D"],
        "matieres": ["Maths", "SPCT", "SVT"],
        "bourses": "117",
        "aides": "0",
        "debouches": "Médecin généraliste dans les hôpitaux et centre de santé."
    },
    {
        "univ": "UP",
        "ecole": "ENATSE",
        "nom_complet": "Ecole Nationale de formation des Techniciens Supérieurs en Santé Publique et Surveillance Epidémiologique",
        "nom": "Santé publique et surveillance épidémiologique",
        "mode": "Classement",
        "series": ["C", "D"],
        "matieres": ["Maths", "Anglais", "SVT"],
        "bourses": "34",
        "aides": "0",
        "debouches": "Biostatisticien dans les services de Santé\nAgent de Surveillance épidémiologique\nAttaché de Recherche dans les Instituts de Recherche en Santé\nAgent des collectivités locales."
    },
    {
        "univ": "UP",
        "ecole": "IFSIO",
        "nom_complet": "Institut de Formation en Soins Infirmiers et Obstétricaux",
        "nom": "Soins Infirmiers",
        "mode": "Concours",
        "series": ["C", "D"],
        "matieres": ["PCT", "SVT"],
        "bourses": "31",
        "aides": "0",
        "debouches": "Infirmier diplômé d’Etat."
    },
    {
        "univ": "UP",
        "ecole": "IFSIO",
        "nom_complet": "Institut de Formation en Soins Infirmiers et Obstétricaux",
        "nom": "Soins obstétricaux",
        "mode": "Concours",
        "series": ["C", "D"],
        "matieres": ["PCT", "SVT"],
        "bourses": "44",
        "aides": "0",
        "debouches": "Sage-Femme diplômée d’Etat"
    },
    {
        "univ": "UP",
        "ecole": "IUT",
        "nom_complet": "Institut Universitaire de Technologie",
        "nom": "Gestion des Banques",
        "mode": "Classement",
        "series": ["C", "D", "G2"],
        "matieres": ["Maths (C, D)/Etude de Cas (G)", "Français", "Anglais"],
        "bourses": "15",
        "aides": "0",
        "debouches": "Organismes financiers ou de gestion (établissement de crédits, entreprises commerciales de banque)"
    },
    {
        "univ": "UP",
        "ecole": "IUT",
        "nom_complet": "Institut Universitaire de Technologie",
        "nom": "Gestion Commerciale",
        "mode": "Classement",
        "series": ["C", "D", "G3", "B", "DT/CoM"],
        "matieres": ["Maths (B, C, D)/Etude de Cas (G)", "Français", "Anglais (LV1)", "Techn Compta et Mercat que (DT)", "Organisation et Administration (DT)", "rationnelle des ressources Français (DT)"],
        "bourses": "8",
        "aides": "0",
        "debouches": "Entreprises commerciales ou services commerciaux de tout type d’entreprise\nServices de logistiques internationale\nEntreprise d’export\nSociétés de transit et de manutention, banque, agence de communication, grandes entreprises de représentant commercial de chef de rayon dans le centre commercial (supermarché), d’attaché commercial de chef de produit, chargé des relations publiques, assistant de communication interne diffusant des informations à l’intérieur de l’entreprise."
    },
    {
        "univ": "UP",
        "ecole": "IUT",
        "nom_complet": "Institut Universitaire de Technologie",
        "nom": "Gestion des Entreprises",
        "mode": "Classement",
        "series": ["C", "D", "G2"],
        "matieres": ["Maths (C, D)/Etude de Cas (G)", "Français", "Anglais"],
        "bourses": "8",
        "aides": "0",
        "debouches": "Cabinets comptables\nServices de comptabilité des entreprises, banque, assurances, administrations, petites, moyennes et grandes entreprises, auto emploi."
    },
    {
        "univ": "UP",
        "ecole": "IUT",
        "nom_complet": "Institut Universitaire de Technologie",
        "nom": "Gestion des Transports et Logistiques",
        "mode": "Classement",
        "series": ["C", "D", "B", "G2"],
        "matieres": ["Maths (B, C, D)/Etude de Cas (G)", "Français", "Anglais (LV1)"],
        "bourses": "14",
        "aides": "0",
        "debouches": "Banque, Société d’assurance et administrations, petites et moyennes entreprises, grandes entreprises, entreprises de transport et de Gestion ferroviaire, service chargé de la logistique au niveau des entreprises, des administrations, poste d’agent comptable dans les compagnies aériennes, d’agent de fret dans les aéroports, de techniciens des études et l’exploitation de l’avion civile"
    },
    {
        "univ": "UP",
        "ecole": "IUT",
        "nom_complet": "Institut Universitaire de Technologie",
        "nom": "Informatique de Gestion",
        "mode": "Classement",
        "series": ["C", "D", "G2"],
        "matieres": ["Maths", "Français/Economie (G2)", "Anglais/Etude de Cas (G2)"],
        "bourses": "59",
        "aides": "0",
        "debouches": "Centre informatique, banque, entreprise de prestation de service, éditeur de logiciels, grandes entreprises informatisées, poste d’analyse programmeur, chef de programme informatique, d’ingénieur logiciel, administrateur de réseau."
    },
    {
        "univ": "UP",
        "ecole": "IUT",
        "nom_complet": "Institut Universitaire de Technologie",
        "nom": "Gestion des Ressources Humaines",
        "mode": "Classement",
        "series": ["A2", "B", "D", "G1", "G2", "G3"],
        "matieres": ["Maths (A2, C, D) / Etude de Cas (G2-G3) / Economie (B-G1)", "Français", "Anglais (LV1)"],
        "bourses": "8",
        "aides": "0",
        "debouches": "Entreprises\nAssurance\nAdministrations\nOrganisations\nONG"
    },
    {
        "univ": "UP",
        "ecole": "ENSPD",
        "nom_complet": "Ecole Nationale de Statistique, de Planification et de Démographie",
        "nom": "Statistiques Appliquées",
        "mode": "Concours",
        "series": ["C", "D"],
        "matieres": ["Non spécifiées (Concours)"],
        "bourses": "22",
        "aides": "0",
        "debouches": "Planificateur dans les ministères sectoriels\nAdministrations nationales et communales\nCentres ou laboratoires de recherche et cabinets d’études ;"
    },
    {
        "univ": "UP",
        "ecole": "ENSPD",
        "nom_complet": "Ecole Nationale de Statistique, de Planification et de Démographie",
        "nom": "Planification et Suivi Evaluation",
        "mode": "Concours",
        "series": ["C", "D"],
        "matieres": ["Culture Générale", "Maths"],
        "bourses": "21",
        "aides": "0",
        "debouches": "Centres ou laboratoires de recherche et cabinets d’études ;\nProjets de développement et ONG ;\nServices de consultation (individuelle ou institutionnelle) ;\nMilieux hospitaliers ;\nBanques, structures de finance et de microfinance ;\nsociétés pharmaceutiques ;\nMaison de sondages ;\nDirection Nationale de la Statistique ;\nEnseignant universitaire ;\nRecherche."
    },
    {
        "univ": "UP",
        "ecole": "FASEG",
        "nom_complet": "Faculté de Sciences Economiques et de Gestion",
        "nom": "Analyse et Politique Economiques (APE)",
        "mode": "Classement",
        "series": ["B", "C", "D", "G2", "G3"],
        "matieres": ["Maths (C, D) / Etude de Cas (G) / Economie (B)", "Français", "Anglais (LV1)"],
        "bourses": "24",
        "aides": "42",
        "debouches": "Auto emploi ;\nCabinets Conseils en Politiques Economiques ;\nCabinets Conseils en Projets de Développement ;\nCabinets de Suivi et Evaluation de Projets de Développement Structures Chargées des Questions Liées aux Affaires Economiques (ONG ; Ministère ; Administrations ; Projets de Développement ; Entreprises de tous genres)."
    },
    {
        "univ": "UP",
        "ecole": "FASEG",
        "nom_complet": "Faculté de Sciences Economiques et de Gestion",
        "nom": "Economie Agricole (EA)",
        "mode": "Classement",
        "series": ["B", "C", "D", "G2", "G3"],
        "matieres": ["Maths (C, D) / Etude de Cas (G) / Economie (B)", "Français", "Anglais (LV1)"],
        "bourses": "62",
        "aides": "96",
        "debouches": "Auto emploi ;\nCabinets Conseils en Politiques Economiques ;\nCabinets Conseils en Projets de Développement ;\nCabinets de Suivi et Evaluation de Projets de Développement Structures Chargées des Questions Liées aux Affaires Economiques (ONG ; Ministère ; Administrations ; Projets de Développement ; Entreprises de tous genres)."
    },
    {
        "univ": "UP",
        "ecole": "FASEG",
        "nom_complet": "Faculté de Sciences Economiques et de Gestion",
        "nom": "Economie et Finance des Collectivités Locales (EFCL)",
        "mode": "Classement",
        "series": ["B", "C", "D", "G2", "G3"],
        "matieres": ["Maths (C, D) / Etude de Cas (G) / Economie (B)", "Français", "Anglais (LV1)"],
        "bourses": "23",
        "aides": "42",
        "debouches": "Auto emploi ;\nCabinets Conseils en Economie et Finance des Collectivités Locales;\nCabinets Conseils en Projets de Développement Local;\nCabinets de Suivi et Evaluation de Projets de Développement Locaux;\nGestion Financière de Structures Chargées des Questions Liées aux Affaires Economiques et Financières des Collectivités Territoriales Décentralisées (Ministères ; Administrations ; Projets de Développement ; Mairies) ;\nStructures Chargées des Questions Liées à la Promotion de l’Economie et de la Fiscalité des Collectivités Territoriales Décentralisées (Ministères ; Administrations ; Projets de Développement ; Mairies)."
    },
    {
        "univ": "UP",
        "ecole": "FDSP",
        "nom_complet": "Faculté de Droit et Sciences Politiques",
        "nom": "Droit Privé",
        "mode": "Classement",
        "series": ["A1", "A2", "B", "C", "D", "G1", "G2", "G3"],
        "matieres": ["Français", "Philosophie / Etude de cas (G)", "Hist-Géo / Anglais (G)"],
        "bourses": "99",
        "aides": "545",
        "debouches": "Attaché des services administratifs ;\nJuristes des affaires ;\nGreffier ;\nCollaborateurs de profession judiciaire (avocats, huissiers, notaires, Commissaires-priseurs) ;\nMagistrature (à condition de compléter le cycle de master) ;\nconsultant ;\npolicier ;\nmilitaire."
    },
    {
        "univ": "UP",
        "ecole": "FDSP",
        "nom_complet": "Faculté de Droit et Sciences Politiques",
        "nom": "Droit Public",
        "mode": "Classement",
        "series": ["A1", "A2", "B", "C", "D", "G1", "G2", "G3"],
        "matieres": ["Français", "Philosophie / Etude de cas (G)", "Hist-Géo / Anglais (G)"],
        "bourses": "75",
        "aides": "341",
        "debouches": "Attaché de services administratifs ;\nJuristes des affaires ;\nGreffier ;\nCollaborateurs de profession judiciaire (avocats, huissiers, notaires, Commissaires-priseurs) ;\nMagistrature (à condition de compléter le cycle de master) ;\nconsultant ;\npolicier ;\nmilitaire ;\nattaché des services financiers ;\nattaché des impôts ;\nassistant juridique."
    },
    {
        "univ": "UP",
        "ecole": "FDSP",
        "nom_complet": "Faculté de Droit et Sciences Politiques",
        "nom": "Sciences Politiques et Relations Internationales",
        "mode": "Classement",
        "series": ["A1", "A2", "B", "C", "D", "G1", "G2", "G3"],
        "matieres": ["Français", "Philosophie / Etude de cas (G)", "Hist-Géo / Anglais (G)"],
        "bourses": "41",
        "aides": "129",
        "debouches": "publique et locale ;\ndiplomatie ;\nagents des services extérieurs et diplomatique ;\nattaché politique ;\nattaché des services culturels ;\nguides touristiques ;\nconseillé politique ;\nanalyste de politique publique ;\nlobbyiste ;\nagents des services parlementaires ;\nmédiateur ;\ndéputé ;\nagents de relation publiques ;\nfonctionnaires"
    },
    {
        "univ": "UP",
        "ecole": "FLASH",
        "nom_complet": "Faculté des Lettres, Arts et Sciences Humaines",
        "nom": "Allemand",
        "mode": "Classement",
        "series": ["A1", "A2", "B"],
        "matieres": ["Français", "Philo", "Allemand (LV1)"],
        "bourses": "36",
        "aides": "195",
        "debouches": "Enseignement\nInterprète, Traducteur\nAgent dans le tourisme"
    },
    {
        "univ": "UP",
        "ecole": "FLASH",
        "nom_complet": "Faculté des Lettres, Arts et Sciences Humaines",
        "nom": "Anglais",
        "mode": "Classement",
        "series": ["A1", "A2", "B", "C", "D", "DEAT (Toutes les options)"],
        "matieres": ["Français", "Anglais (LV1)", "Maths", "DEAT : Prendre en compte les matières écrites"],
        "bourses": "141",
        "aides": "424",
        "debouches": "Enseignement\nInterprète, Traducteur\nAgent dans le tourisme"
    },
    {
        "univ": "UP",
        "ecole": "FLASH",
        "nom_complet": "Faculté des Lettres, Arts et Sciences Humaines",
        "nom": "Espagnol",
        "mode": "Classement",
        "series": ["A1", "A2", "B"],
        "matieres": ["Français", "Philo", "Espagnol (LV1)"],
        "bourses": "38",
        "aides": "244",
        "debouches": "Enseignement\nInterprète, Traducteur\nAgent dans le tourisme"
    },
    {
        "univ": "UP",
        "ecole": "FLASH",
        "nom_complet": "Faculté des Lettres, Arts et Sciences Humaines",
        "nom": "Géographie et Aménagement du Territoire",
        "mode": "Classement",
        "series": ["A1", "A2", "B", "C", "D", "DEAT (Toutes les options)"],
        "matieres": ["Français", "Anglais (LV1)", "Maths", "DEAT : Prendre en compte les matières écrites"],
        "bourses": "101",
        "aides": "431",
        "debouches": "Enseignement\nUrbaniste, Climatologiste\nGéomorphologue, Hydrologue."
    },
    {
        "univ": "UP",
        "ecole": "FLASH",
        "nom_complet": "Faculté des Lettres, Arts et Sciences Humaines",
        "nom": "Sociologie Anthropologie",
        "mode": "Classement",
        "series": ["A1", "A2", "B", "C", "D", "DEAT (Toutes les options)"],
        "matieres": ["Français", "Anglais (LV1)", "Maths", "DEAT : Prendre en compte les matières écrites"],
        "bourses": "115",
        "aides": "503",
        "debouches": "Employé dans les centres Sociaux, Centre de recherche, Ministère, ONG, Projet.\nMédiateur."
    },
    {
        "univ": "UP",
        "ecole": "FLASH",
        "nom_complet": "Faculté des Lettres, Arts et Sciences Humaines",
        "nom": "Lettres Modernes",
        "mode": "Classement",
        "series": ["A1", "A2"],
        "matieres": ["Français", "Philosophie", "Hist-Géo"],
        "bourses": "230",
        "aides": "444",
        "debouches": "Enseignement\nInterprète, Traducteur"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Comptabilité",
        "mode": "Concours",
        "series": ["B", "G2", "G3", "C", "D", "DT/COM"],
        "matieres": ["Culture générale", "Etude de cas (G) / Maths (C, D) / Economie (B) / Techn Compta et Mercatique (DT/COM)"],
        "bourses": "9",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Economie",
        "mode": "Concours",
        "series": ["B", "G2", "G3", "C", "D", "DT/COM"],
        "matieres": ["Culture générale", "Etude de cas (G) / Maths (C, D) / Economie (B) / Techn Compta et Mercatique (DT/COM)"],
        "bourses": "12",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Electrotechnique",
        "mode": "Concours",
        "series": ["C", "D", "F2", "F3", "DT / Electricité", "DT / Electrotechnique Appliquée"],
        "matieres": ["Culture générale", "PCT (C, D)", "Electrotech (F2, F3, DT/Electricité, DT/ Electrotech Appliqué)"],
        "bourses": "30",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Génie Civil",
        "mode": "Concours",
        "series": ["C", "D", "F4", "DT/BTP"],
        "matieres": ["Culture générale", "PCT (C, D) / RDM (F4, DT/BTP)"],
        "bourses": "34",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Secrétariat",
        "mode": "Concours",
        "series": ["A1", "A2", "B", "G1"],
        "matieres": ["Culture générale", "BS (G1) / Histoire (A1, A2) / Economie (B)"],
        "bourses": "6",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Mécanique Automobile",
        "mode": "Concours",
        "series": ["C", "D", "F2", "DT/MA"],
        "matieres": ["Culture générale", "PCT (C, D) / Technologie Automobile (DT/MA) / Dessin Industriel (F2)"],
        "bourses": "28",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Fabrication Mécanique",
        "mode": "Concours",
        "series": ["C", "D", "E", "F1", "DT/FM"],
        "matieres": ["Culture générale", "PCT (C, D) / RDM (E, F1, DT/FM)"],
        "bourses": "22",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Economie Familiale et Sociale",
        "mode": "Concours",
        "series": ["A1", "A2", "B", "C", "D", "DT/EFS"],
        "matieres": ["Culture générale", "PCT (C, D) / Educ santé (DT/EFS) / Anglais (A1, A2) / Economie (B)"],
        "bourses": "5",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Hôtellerie-Restauration",
        "mode": "Concours",
        "series": ["A1", "A2", "B", "C", "D", "DT/HR", "DT/Tourisme", "DT/EFS"],
        "matieres": ["Culture générale", "PCT (C, D) / Tech BR (DT/HR) / Hist (A1, A2) / Economie (B) / Anglais (DT/Tourisme) / Puériculture (DT/EFS)"],
        "bourses": "36",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Froid et Climatisation",
        "mode": "Concours",
        "series": ["C", "D", "E", "F3", "DT/FC"],
        "matieres": ["Culture générale", "PCT (C, D) / Tech Froid (DT/FC) / Electrotechnique (F3) / RDM (E)"],
        "bourses": "27",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Electronique",
        "mode": "Concours",
        "series": ["C", "D", "F2", "DT/EAp"],
        "matieres": ["Culture générale", "PCT (C, D) / EST (F2) / Pour DT/EAp ; Sciences Appliquées Français / Etude Electronique"],
        "bourses": "14",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Energies Renouvelables",
        "mode": "Concours",
        "series": ["C", "D", "F2", "F3", "DT/Electricité", "DT/Eap"],
        "matieres": ["Culture générale", "PCT (C, D) / Mathématiques Appliquées (F2, F3, DT/Electricité) / Pour DT/EAp ; Sciences Appliquées Français / Etude Electronique"],
        "bourses": "34",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Production Animale",
        "mode": "Concours",
        "series": ["C", "D", "DEAT/PA", "DEAT/PV"],
        "matieres": ["Culture générale", "SVT (D)/PCT (C) / Agriculture spéciale (DEAT/PV)/ Zootechnie spéciale (DEAT/PA)"],
        "bourses": "13",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSET",
        "nom_complet": "Ecole Normale Supérieure de l'Enseignement technique",
        "nom": "Production végétale",
        "mode": "Concours",
        "series": ["Non spécifiées (Concours)"],
        "matieres": ["Non spécifiées (Concours)"],
        "bourses": "8",
        "aides": "0",
        "debouches": "Professeur adjoint des Lycées et Collèges"
    },
    {
        "univ": "UNSTIM",
        "ecole": "INSTI",
        "nom_complet": "Institut National Supérieur de Technologie Industrielle",
        "nom": "Génie Civil",
        "mode": "Classement",
        "series": ["C", "D", "E", "F4", "DT/BTP", "DT/OG", "DT/DPB"],
        "matieres": ["Maths", "SPCT", "Anglais (C, D) / Construction Mécanique (E) / Béton Armé (F4)/ RDM (DT/BTP, DT/DPB) / Technologie (DT/OG)"],
        "bourses": "68",
        "aides": "0",
        "debouches": "Techniciens de Travaux du Génie Civil\nControleurs de chantiers\nAssistant des Experts Géomètres, des cabinets d’architecture, des agences immobilières et des notaires"
    },
    {
        "univ": "UNSTIM",
        "ecole": "INSTI",
        "nom_complet": "Institut National Supérieur de Technologie Industrielle",
        "nom": "Génie Energétique (Energies Renouvelables et Systèmes Energétiques)",
        "mode": "Classement",
        "series": ["C", "D", "E", "F2", "F3", "DT/(Electrotech)", "DT/Eap"],
        "matieres": ["Maths", "SPCT", "Anglais (C, D)/ Construction Mécanique (E)/Electrotech (F3, DT/Electrotech) / EST (F2)", "Pour DT/EAP ; Sciences Appliquées Français", "Etude Electronique"],
        "bourses": "37",
        "aides": "0",
        "debouches": "Techniciens en Industrie électrique, électrotechniques et électroniques\nMétiers du bâtiment\nAppareillage, instrumentation\nInstallations, équipements et systèmes pour énergies renouvelables\nAudit et Efficacité énergétique"
    },
    {
        "univ": "UNSTIM",
        "ecole": "INSTI",
        "nom_complet": "Institut National Supérieur de Technologie Industrielle",
        "nom": "Génie Energétique (Froid et climatisation)",
        "mode": "Classement",
        "series": ["C", "D", "E", "F3", "DT/(Electrotech, Froid et Climatisation)"],
        "matieres": ["Maths", "SPCT (C, D, E, F3) ou Technique de Froid (DT/FC)", "Anglais (C, D)/ Technologie de spécialité (DT-Froid et climatisation)/Electrotech (F3, DT/Electrotech) /Construction mécanique (E)"],
        "bourses": "30",
        "aides": "0",
        "debouches": "Techniciens en Froid et climatisation de bâtiment et automobile\nMétiers du bâtiment\nAppareillage, instrumentation"
    },
    {
        "univ": "UNSTIM",
        "ecole": "INSTI",
        "nom_complet": "Institut National Supérieur de Technologie Industrielle",
        "nom": "Génie Electrique et Informatique (Informatique et Télécommunications)",
        "mode": "Classement",
        "series": ["C", "D", "E", "F3", "DT/(Electrotech, Appliquée)"],
        "matieres": ["Maths", "Anglais (C, D)/ Construction Mécanique (E)/ Electrotech (F3, DT/Electrotech)", "SPCT"],
        "bourses": "24",
        "aides": "0",
        "debouches": "Service informatique d’entreprise\nCabinets d’audit ou ingénierie informatique\nSociétés de maintenance informatique\nAgences de communication\nAgences de développement d’applications web et mobiles\nSociétés de téléphonie mobile\nFournisseurs d’accès internet\nTélésurveillance\nSystèmes embarqués"
    },
    {
        "univ": "UNSTIM",
        "ecole": "INSTI",
        "nom_complet": "Institut National Supérieur de Technologie Industrielle",
        "nom": "Génie Electrique et Informatique (Electronique et Electrotechnique)",
        "mode": "Classement",
        "series": ["C", "D", "E", "F3", "DT/Electrotech"],
        "matieres": ["Maths", "SPCT", "Anglais (C, D) / Construction Mécanique (E)/ Electrotech (F3, DT/Electrotech)"],
        "bourses": "26",
        "aides": "0",
        "debouches": "Electricité Industrielle et de bâtiments\nContrôle de procédés dans le domaine électrique\nÉnergie électrique, sa production, son transport et son traitement\nCommande automatique de processus\nSystèmes embarqués\nTélésurveillance\nContrôle de Qualité dans le domaine électrique"
    },
    {
        "univ": "UNSTIM",
        "ecole": "INSTI",
        "nom_complet": "Institut National Supérieur de Technologie Industrielle",
        "nom": "Maintenance des Systèmes (Maintenance Industrielle)",
        "mode": "Classement",
        "series": ["F1", "F2", "F3", "DT/Froid et Climatisation", "DT/Electrotechnique"],
        "matieres": ["Maths", "SPCT", "Construction Mécanique (F1, F2) / EST(F3)", "Pour les DT : Maths", "Technique de Froid (DT/FC) / Electrotech (DT-Electrotech)", "Technologie de Spécialité (DT/FC) / EST(DT-Electrotech)"],
        "bourses": "21",
        "aides": "0",
        "debouches": "Techniciens des industries de transformation et Unités de production alimentaire\nAuditeurs /Conseils des Entreprises ou Sociétés de TP\nResponsable service après-vente"
    },
    {
        "univ": "UNSTIM",
        "ecole": "INSTI",
        "nom_complet": "Institut National Supérieur de Technologie Industrielle",
        "nom": "Maintenance des Systèmes (Maintenance Automobile)",
        "mode": "Classement",
        "series": ["F1", "F2", "DT/MA"],
        "matieres": ["Maths", "SPCT", "Construction Mécanique (F1, F2)/Mécanique (DT-MA)"],
        "bourses": "25",
        "aides": "0",
        "debouches": "Parcs automobiles\nConcessionnaires automobiles\nGestionnaires de parc d’engins agricoles ou de manutention\nUsines de production\nCabinet d’expertise et de Conseils\nEntreprise et Sociétés de BTP\nEquipementiers automobiles"
    },
    {
        "univ": "UNSTIM",
        "ecole": "INSTI",
        "nom_complet": "Institut National Supérieur de Technologie Industrielle",
        "nom": "Génie Mécanique et productique",
        "mode": "Classement",
        "series": ["C", "D", "E", "F1", "DT/MA", "DT/FM"],
        "matieres": ["Maths", "SPCT", "Anglais (C, D) / Construction Mécanique (E, F1, DT/FM) / Mécanique (DT/MA)"],
        "bourses": "38",
        "aides": "0",
        "debouches": "Maintenance industrielle\nFabrication mécanique\nParcs machines\nMéthodes et contrôle de la qualité\nMaintenance des engins agricoles\nMécanisation agricole"
    },
    {
        "univ": "UNSTIM",
        "ecole": "INSPEI",
        "nom_complet": "Institut National Supérieur des Classes Préparatoires aux Etudes d'Ingénieurs",
        "nom": "Sciences et Techniques de l’Ingénieur",
        "mode": "Concours",
        "series": ["C", "D", "E"],
        "matieres": ["PCT", "Maths"],
        "bourses": "83",
        "aides": "0",
        "debouches": "Ingénieur de conception (apres 3 ans d'etudes dans les ecoles d'ingénieur au sein de l'UNSTIM)"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENS/Nati",
        "nom_complet": "Ecole Normale Supérieure de Natitingou",
        "nom": "Mathématiques et Informatique (MI)",
        "mode": "Concours",
        "series": ["C", "D"],
        "matieres": ["Culture générale", "Maths"],
        "bourses": "29",
        "aides": "0",
        "debouches": "Professeur Adjoint de Maths"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENS/Nati",
        "nom_complet": "Ecole Normale Supérieure de Natitingou",
        "nom": "Physique, Chimie et Technologie (PCT)",
        "mode": "Concours",
        "series": ["C", "D"],
        "matieres": ["Culture générale", "PCT"],
        "bourses": "17",
        "aides": "0",
        "debouches": "Professeur Adjoint de PCT"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENS/Nati",
        "nom_complet": "Ecole Normale Supérieure de Natitingou",
        "nom": "Sciences de la Vie et de la Terre (SVT)",
        "mode": "Concours",
        "series": ["C", "D"],
        "matieres": ["Culture générale", "SVT"],
        "bourses": "12",
        "aides": "0",
        "debouches": "Professeur Adjoint de SVT"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSBBA",
        "nom_complet": "Ecole Nationale Supérieure des Biosciences et Biotechnologies Appliquées",
        "nom": "Biotechnologie Médicale",
        "mode": "Classement",
        "series": ["C", "D"],
        "matieres": ["SVT", "PCT", "Maths"],
        "bourses": "11",
        "aides": "0",
        "debouches": "Techniciens supérieurs dans les Laboratoires de diagnostics biomédicaux et de contrôle de qualité des analyses ;\nTechniciens supérieurs dans les Laboratoires de recherche universitaire ou privés ;\nTechnicien supérieur dans les Laboratoires de production de bioproduits ;\nAuto-emploi"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSBBA",
        "nom_complet": "Ecole Nationale Supérieure des Biosciences et Biotechnologies Appliquées",
        "nom": "Biotechnologie Pharmaceutique (BP)",
        "mode": "Classement",
        "series": ["C", "D"],
        "matieres": ["SVT", "PCT", "Maths"],
        "bourses": "10",
        "aides": "0",
        "debouches": "Techniciens supérieurs de valorisation des ressources biologiques et de l’Environnement dans les industries pharmaceutiques et cosmétiques\nTechniciens supérieurs dans les laboratoires de substances naturelles et de fabrication des bioproduits\nTechniciens supérieurs dans les laboratoires de contrôle de qualité des produits pharmaceutiques et cosmétiques\nTechniciens supérieurs dans les laboratoires de recherche ;\nTechniciens supérieurs dans les laboratoires pédagogiques des universités\nAuto-emploi"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSBBA",
        "nom_complet": "Ecole Nationale Supérieure des Biosciences et Biotechnologies Appliquées",
        "nom": "Génétique Biotechnologies et Applications",
        "mode": "Classement",
        "series": ["C", "D"],
        "matieres": ["SVT", "PCT", "Maths"],
        "bourses": "10",
        "aides": "0",
        "debouches": "Recherches en génétique et biotechnologies appliquées\nTechnicien supérieur en gestion des ressources génétiques\nTechnicien supérieur en conception de tests génétiques de diagnostic des maladies génétiques\nEntrepreneuriat et sélections végétales et animales"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSBBA",
        "nom_complet": "Ecole Nationale Supérieure des Biosciences et Biotechnologies Appliquées",
        "nom": "Génie Biologique et Bioprocédés (GBB)",
        "mode": "Classement",
        "series": ["C", "D"],
        "matieres": ["SVT", "PCT", "Maths"],
        "bourses": "15",
        "aides": "0",
        "debouches": "Techniciens supérieurs dans les laboratoires d'analyse ou de recherche\nTechniciens supérieurs des centres de recherche en biologie appliquée\nAssistant de recherche dans les instituts de recherche biologique ;\nAuto-emploi"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSBBA",
        "nom_complet": "Ecole Nationale Supérieure des Biosciences et Biotechnologies Appliquées",
        "nom": "Diététique des aliments et Nutrition",
        "mode": "Classement",
        "series": ["C", "D"],
        "matieres": ["SVT", "PCT", "Maths"],
        "bourses": "9",
        "aides": "0",
        "debouches": "Technicien supérieur en diététique\nTechnicien supérieur en contrôle de qualité des aliments\nTechnicien dans les sociétés de restauration collective\nTechnicien supérieur nutritionnistes des centres hospitaliers et des maisons de repos\nConseiller en éducation nutritionnelle et alimentaire\nAuto-emploi"
    },
    {
        "univ": "UNSTIM",
        "ecole": "FAST/Natitingou",
        "nom_complet": "Faculté des Sciences et Techniques de Natitingou",
        "nom": "Mathématiques Informatiques",
        "mode": "Classement",
        "series": ["C", "D"],
        "matieres": ["Anglais", "PCT", "Maths"],
        "bourses": "83",
        "aides": "43",
        "debouches": "Cadres de télécommunications optiques et des nouvelles technologies de l’information et de la communication ;\nEnseignants des lycées et collèges (BAPES et CAPES en MI) après complément de formation en sciences de l’éducation ;\nAccès aux écoles d’ingénieur ;\nAccès à un master recherche ou professionnel en mathématique ou en informatique pouvant déboucher sur une thèse de doctorat."
    },
    {
        "univ": "UNSTIM",
        "ecole": "FAST/Natitingou",
        "nom_complet": "Faculté des Sciences et Techniques de Natitingou",
        "nom": "Physique Chimie",
        "mode": "Classement",
        "series": ["C", "D"],
        "matieres": ["Anglais", "PCT", "Maths"],
        "bourses": "66",
        "aides": "28",
        "debouches": "Cadres de télécommunications optiques et des nouvelles technologies de l’information et de la communication ;\nCadres en Météorologie, océanographie et balistique ;\nEnseignants des lycées et collèges (BAPES et CAPES en PCT) après complément de formation en sciences de l’éducation ;\nAccès aux écoles d’ingénieur ;\nAccès à un master professionnel de physique ou de technologie ;\nAccès à un master recherche en vue d’approfondir les connaissances théoriques en physique ou en chimie fondamentale et de réaliser une thèse de doctorat ;\nCadres des industries chimiques (cosmétique, parfumerie et cimenterie), agroalimentaires (brasseries, huileries…) et pharmaceutiques."
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSGEP",
        "nom_complet": "Ecole Nationale Supérieure de Génie Energétique et Procédés",
        "nom": "Froid et Climatisation",
        "mode": "Classement",
        "series": ["C", "D", "DT/Froid et Clim"],
        "matieres": ["Maths", "Anglais", "SPCT(C,D) / TF (DT/Froid et Clim)"],
        "bourses": "25",
        "aides": "0",
        "debouches": "Technicien supérieur en Installation, mise en service et maintenance d’équipements de froid et climatisation"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSGEP",
        "nom_complet": "Ecole Nationale Supérieure de Génie Energétique et Procédés",
        "nom": "Equipements motorisés",
        "mode": "Classement",
        "series": ["C", "D", "E", "DT/MA", "DT/FM"],
        "matieres": ["Maths", "Anglais / Français (E)", "SPCT (C, D) / Mécanique (DT/MA) / Construction Mécanique (E, DT/FM)"],
        "bourses": "24",
        "aides": "0",
        "debouches": "Technicien supérieur en Installation et maintenance des équipements motorisés;\nElectromécanique; Mécanique automobile;\nInstallation et maintenance de matériels électroménagers;\nMaintenance des systèmes hydrauliques et pneumatiques des gros engins des travaux publics"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSTP",
        "nom_complet": "Ecole Nationale Supérieure des Travaux Publics",
        "nom": "Génie Civil",
        "mode": "Classement",
        "series": ["C", "D", "E", "EA", "F4", "DT/BTP"],
        "matieres": ["Maths", "Anglais / Français (E, F4)", "SPCT (C, D, E) / RDM (F4, DT/BTP) / Assainissement (EA)"],
        "bourses": "21",
        "aides": "0",
        "debouches": "Assistants dans les bureaux d’études ;\nTechniciens contrôleurs de travaux du Génie Civil (routes, bâtiments, ouvrages d’art, assainissement, aménagements divers…) ;\nTechniciens métreur ou technicien assistant des ingénieurs études ;\nTechniciens dans les services déconcentrés et Mairies ;\nTechniciens de laboratoires géotechniques ou de recherche en génie civil ;\nAssistants des Experts Routiers, géotechniciens, ouvragistes ;\nEntrepreneur, chef de chantier ;\nConducteur de travaux"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSTP",
        "nom_complet": "Ecole Nationale Supérieure des Travaux Publics",
        "nom": "Génie Géomatique Appliquée",
        "mode": "Classement",
        "series": ["C", "D", "F4", "DT/OG", "DT/BTP"],
        "matieres": ["Maths", "Anglais / Français (F4)", "SPCT (C, D) / RDM (F4, DT/BTP) / Technologie (DT/OG)"],
        "bourses": "21",
        "aides": "0",
        "debouches": "Assistants des Experts Géomètres, des architectes, agences immobilières et notaires ;\nTechniciens en Système d’Information Géographique (SIG) ;\nTechnicien-Cartographes ;\nTechnicien dans les Services déconcentrés et Mairies ;\nAssistants dans les bureaux d’études"
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSTP",
        "nom_complet": "Ecole Nationale Supérieure des Travaux Publics",
        "nom": "Architecture et Urbanisme",
        "mode": "Classement",
        "series": ["C", "D", "F4", "DT/OG", "DT/BTP"],
        "matieres": ["Maths", "Anglais / Français (F4)", "SPCT (C, D) / RDM (F4, DT/BTP) / Technologie (DT/OG)"],
        "bourses": "26",
        "aides": "0",
        "debouches": "Techniciens Architectes-Urbanistes ;\nTechniciens Contrôleurs de chantiers de bâtiments ;\nTechniciens Contrôleurs de travaux d’aménagements urbains ;\nAssistants des experts aménagistes urbanistes ;\nTechniciens dans les services déconcentrés et les Mairies ;\nAssistants dans les Cabinets d’Architecture, agences immobilières et notaires ;\nAssistants dans les bureaux d’études."
    },
    {
        "univ": "UNSTIM",
        "ecole": "ENSTP",
        "nom_complet": "Ecole Nationale Supérieure des Travaux Publics",
        "nom": "Hydraulique et Assainissement",
        "mode": "Classement",
        "series": ["C", "D", "E", "EA", "F4"],
        "matieres": ["Maths", "Anglais / Français (E, F4)", "SPCT (C, D, E) / RDM (F4) / Assainissement (EA)"],
        "bourses": "25",
        "aides": "0",
        "debouches": "Techniciens en Hydraulique et Assainissement ;\nTechniciens de Laboratoires d’analyse d’eau ;\nTechniciens Contrôleurs : (i) des travaux d’assainissement, (ii) des travaux d’Adduction d’Eaux et (iii) des travaux de constructions d’ouvrages hydrauliques ou hydro-agricoles (barrages, ponts, etc.) ;\nTechnicien de gestion : (i) des stations d’épuration des eaux usées et (ii) des stations de traitements de l’eau pour boisson ;\nTechniciens dans les services déconcentrés et Mairies ;\nAssistants des experts hydrauliciens, hydrologues et en gestion des eaux ;\nAssistants dans les bureaux d’études"
    },
    {
        "univ": "UNA",
        "ecole": "EAq",
        "nom_complet": "Ecole d'Aquaculture",
        "nom": "Aquaculture",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/Pêche et aquaculture", "DEAT/Production animale"],
        "matieres": ["Pour C et D: SVT, Maths, SPCT", "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."],
        "bourses": "31",
        "aides": "0",
        "debouches": "Chargé des entreprises aquacoles ;\nTechnicien en production de poissons ;\nTechnicien en production de crevettes, crabes, huitres et de moules ;\nTechnicien en conception et fabrication des aliments pour les espèces aquacoles d'élevage ;\nTechnicien en conception, fabrication et entretien d'aquarium ;\nTechnicien en conception et fabrication des aliments ;\nTechnicien en aquariologie ;\nTechnicien en production, gestion et certification de semences aquacoles ;\nConseiller/Assistant en aquaculture."
    },
    {
        "univ": "UNA",
        "ecole": "EHAEV",
        "nom_complet": "Ecole d'Horticulture et d'Aménagement des Espaces Verts",
        "nom": "Horticulture et Aménagement des espaces Verts",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/PV", "DEAT/Foresterie"],
        "matieres": ["Pour C et D: SVT, Maths, SPCT", "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."],
        "bourses": "55",
        "aides": "0",
        "debouches": "Technicien en gestion des entreprises horticoles (cultures maraîchères, fruitières et ornementales) ;\nConseiller des exploitations des secteurs horticoles (fruits, légumes et ornement) ;\nTechnicien en aménagement des Espaces Verts ;\nTechnicien en production de semences et plants horticoles (maraîchères, fruitières et ornementales) ;\nTechnicien en installation et gestion des systèmes d’irrigation en horticulture et espaces verts (privés et publics) ;\nTechnicien en gestion des ravageurs et nuisibles en horticulture et espaces verts (privés et publics) ;\nTechnicien en conception, installation et réalisation des plans d’aménagement des Espaces Verts (Publics ou privés) ;\nTechnicien en production et distribution d’intrants et de produits horticoles (fruits, légumes et fleurs) ;\nTechnicien en stockage et conditionnement des produits horticoles ;\nTechnicien en cultures hydroponiques et Aquaponiques ;\nTechnicien en biotechnologies horticoles et création variétale ;\nConseiller technique en construction des infrastructures et équipements horticoles et en aménagement des espaces verts ;\nAgent des cabinets d’expertise ;\nTechnicien de recherche en horticulture ;\nFonctionnaire des organisations internationales de développement (Bioversity, ICRAF, World Vegetable, IRD, CIRAD, IITA etc. ) ;\nEnseignant dans les établissements de formation (Ecoles, Lycées Agricoles, Universités, Instituts de formation)."
    },
    {
        "univ": "UNA",
        "ecole": "EGPVS",
        "nom_complet": "Ecole de Gestion et de Production Végétale et Semencière",
        "nom": "Gestion et Production Végétale et Semencière",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/PV"],
        "matieres": ["Pour C et D: SVT, Maths, SPCT", "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."],
        "bourses": "60",
        "aides": "0",
        "debouches": "Entrepreneur en production végétale ;\nTechnicien en production végétale ;\nTechnicien en production de semences et gestionnaire des banques de semences;\nTechnicien en gestion de la fertilité des sols;\nAssistants en élaboration des plans d’entreprise de production végétale et semencière;\nTechnicien en protection des végétaux;\nTechnicien en biotechnologie végétale;\nAssistant de recherche agricole."
    },
    {
        "univ": "UNA",
        "ecole": "ESTCTPA",
        "nom_complet": "Ecole des Sciences et Techniques de Conservation et de Transformation des Produits Agricoles",
        "nom": "Industrie des Produits Agro-Alimentaires et Nutrition Humaine (IPA-NH)",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/Nutrition et Technologie Alimentaire"],
        "matieres": ["Pour C et D: SVT, Maths, SPCT", "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."],
        "bourses": "23",
        "aides": "0",
        "debouches": "Technicien supérieur en Industrie et entreprises agroalimentaires (productions laitières, céréalières, de viande et produits carnés, de poissons et produits halieutiques, produits des fruits et légumes, etc.) ;\nProducteur et conservateur de produits agroalimentaires ;\nConcepteur et fabricant d’aliments à base des produits agricoles ;\nContrôleur de la qualité des produits agricoles et agroalimentaires ;\nConseiller/Assistant/Encadreur en conservation, et transformation des produits agricoles;\nTechnicien en éducation nutritionnelle (ONG, entreprises, associations, autres) ;\nTechnicien des projets de nutrition ;\nEnseignant dans les lycées techniques agricoles."
    },
    {
        "univ": "UNA",
        "ecole": "ESTCTPA",
        "nom_complet": "Ecole des Sciences et Techniques de Conservation et de Transformation des Produits Agricoles",
        "nom": "Industrie des Bio-Ressources (IBR)",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/Nutrition et Technologie Alimentaire"],
        "matieres": ["Pour C et D: SVT, Maths, SPCT", "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."],
        "bourses": "22",
        "aides": "0",
        "debouches": "Technicien supérieur en industrie des Bio-Ressources ;\nTechnicien supérieur dans les industries cosmétiques et de phytothérapie : savons, lotion, huiles essentielles, parfums ;\nProducteur de biogaz ;\nFabricant d’huiles végétales et de corps gras ;\nFabricant d’aliments pour bétail domestique ;\nConseiller en gestion des procédés post récoltes ;\nTechnicien en traitements chimiques et organiques des produits agricoles en stock ;\nEnseignant dans les lycées techniques agricoles."
    },
    {
        "univ": "UNA",
        "ecole": "ESTCTPA",
        "nom_complet": "Ecole des Sciences et Techniques de Conservation et de Transformation des Produits Agricoles",
        "nom": "Génie de Conditionnement Emballage et Stockage des Produits Alimentaires (GCES)",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/Nutrition et Technologie Alimentaire"],
        "matieres": ["Pour C et D: SVT, Maths, SPCT", "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."],
        "bourses": "24",
        "aides": "0",
        "debouches": "Technicien en génie du conditionnement-emballages et stockage des produits agroalimentaires ;\nTechnicien en contrôle de qualité et normes des produits agroalimentaires ;\nConcepteur d’étiquettes, d’emballages et conditionnements alimentaires ;\nConcepteur de structures de stockage et de conservation : greniers, cribs, silos, magasins/entrepôts ;\nConseiller en emballages divers pour le conditionnement ;\nEnseignant dans les lycées techniques agricoles."
    },
    {
        "univ": "UNA",
        "ecole": "EGR",
        "nom_complet": "Ecole de Génie Rural",
        "nom": "Agroéquipement",
        "mode": "Classement",
        "series": ["C", "D", "E", "F1", "F2", "F3", "DT/FM", "DT/CEMS", "DT/MA", "DT/Electrotech", "DEAT/AER"],
        "matieres": [
            "Pour C et D: Maths, SPCT, Anglais",
            "Pour E, F1, DT/FM, DT/CEMS: Maths, SPCT, Construction mécanique",
            "Pour DT/MA, F2, F3 et DT/Electrotech: Maths, SPCT, Mécanique (DT/MA) ou Electrotechnique (F3, DT/Electrotech) ou EST (F2)",
            "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."
        ],
        "bourses": "16",
        "aides": "0",
        "debouches": "Entreprise de conception et de fabrication des machines ;\nSociété de maintenance des engins et équipements agricoles ;\nEntreprise de motorisée ;\nGérant de parc d’engins ou de machines agricoles ;\nEntreprise d’Installation et maintenance d’équipements agroindustriels ;\nEntreprises et Fermes mécanisées agricoles ;\nIndustries de transformation et Unités de production agroalimentaire (usine d’égrenage, Brasseries, Huileries, etc.) ;\nSociétés de maintenance de Tracteurs et de machines agricoles ;\nCabinets d’audit et de Conseils agricoles ;\nGarage de réparation d’automobiles ;\nAdministration publique ;\nÉtablissements d’enseignement technique."
    },
    {
        "univ": "UNA",
        "ecole": "EGR",
        "nom_complet": "Ecole de Génie Rural",
        "nom": "Electrification Rurale et Energies Renouvelables (ERER)",
        "mode": "Classement",
        "series": ["C", "D", "E", "F1", "F2", "F3", "DT/Electrotech", "DT/EAp"],
        "matieres": [
            "Pour C, D, E et F1: Maths, SPCT, FRANCAIS",
            "Pour F2, F3, et DT/Electrotech: Maths, SPCT, Electrotechnique ou EST (F2)",
            "Pour DT/EAp: Sciences Appliquées, Français, Etude Electronique"
        ],
        "bourses": "17",
        "aides": "0",
        "debouches": "Industries de transformation et Unités de Production (agroalimentaire, cimenterie, production de sucre, lait, brasserie, coton, huile de palme, etc.) ;\nCabinets d’audit et de Conseils en énergies renouvelables ;\nProjets de construction de lignes électriques ;\nProjets d’électrification rurale ;\nEntreprises de BTP ;\nGarages automobiles ;\nEntreprises travaillant dans le secteur du biogaz et autres énergies vertes ;\nFermes et entreprises agropastorales ;\nAdministration publique ;\nÉtablissements d’enseignement technique ;\nEntreprenariat sur les énergies vertes et le développement durable."
    },
    {
        "univ": "UNA",
        "ecole": "EGR",
        "nom_complet": "Ecole de Génie Rural",
        "nom": "Infrastructures Rurales et Assainissement",
        "mode": "Classement",
        "series": ["C", "D", "E", "EA", "F1", "F4", "DT/BTP", "DT/DPB", "DT/OG", "DEAT/AER"],
        "matieres": [
            "Pour C, D, F1 et E: Maths, SPCT, FRANCAIS",
            "Pour F4, DT/BTP et DT/DPB: Maths, SPCT, RDM",
            "Pour EA et DT/OG: Maths, SPCT, Mobilisation des ressources en eau (EA) / DRT (DT/OG)",
            "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."
        ],
        "bourses": "16",
        "aides": "0",
        "debouches": "Entreprise de travaux de constructions d’ouvrages / Réseaux hydrauliques ou hydro-agricoles ;\nEntreprise de travaux d’irrigation et de drainage ;\nEntreprise d’aménagement hydro-agricole ;\nEntreprise de travaux de voirie et réseaux d’adduction d’eau potable ;\nSociétés d’eau et d’assainissement ;\nStations d’épuration d’eaux usées ;\nStations de traitements d’eau ;\nServices Techniques des Mairies ;\nEntreprises ou Sociétés de BTP ;\nMission de contrôle ;\nCabinets d’Architecture ;\nLaboratoires de Génie Civil ;\nCabinets / Bureaux d'études et de conseils ;\nÉtablissements d’enseignement technique."
    },
    {
        "univ": "UNA",
        "ecole": "EGESE",
        "nom_complet": "Ecole de Gestion et d'Exploitation des Systèmes d'Elevage",
        "nom": "Productions et santé animales",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/PA"],
        "matieres": [
            "Pour C, D: Maths, SPCT, SVT",
            "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."
        ],
        "bourses": "57",
        "aides": "0",
        "debouches": "Technicien des fermes d’embouche de bovins, ovins et caprins, porcs, lapins et aulacodes ;\nTechnicien des fermes de production de laits de vaches et chèvres ;\nTechnicien en production des œufs de consommation ;\nTechnicien des centres d’accouvage pour la fourniture des poussins d’un jour ;\nAgent technique des Cliniques et pharmacies vétérinaires ;\nEntrepreneur en fabrication des aliments bétail ;\nGestionnaire des Fermes Agro-vétérinaire ;\nAssistant des structures d’audites des systèmes de production animale ;\nTechnicien des entreprises agro-alimentaires de transformation des produits animaux ;\nAssistant des structures de contrôle de qualité des Denrées Alimentaires d’Origine Animale ;\nEnseignant des lycées techniques agricoles."
    },
    {
        "univ": "UNA",
        "ecole": "EAPA",
        "nom_complet": "Ecole d'Agrobusiness et de Politiques Agricoles",
        "nom": "Finance Agricole (FA)",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/Toutes les options"],
        "matieres": [
            "Pour C, D: Maths, SPCT, SVT",
            "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."
        ],
        "bourses": "16",
        "aides": "7",
        "debouches": "Banquier agricole ;\nAssureur agricole ;\nGestionnaire d’institutions de financement agricole ;\nAnalyste des politiques de développement agricole ;\nEntrepreneur agricole ;\nConsultant ;\nEnseignant de collèges et lycées agricoles."
    },
    {
        "univ": "UNA",
        "ecole": "EAPA",
        "nom_complet": "Ecole d'Agrobusiness et de Politiques Agricoles",
        "nom": "Gestion des Exploitations Agricoles et Entreprises Agroalimentaires (GEAEA)",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/Toutes les options"],
        "matieres": [
            "Pour C, D: Maths, SPCT, SVT",
            "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."
        ],
        "bourses": "36",
        "aides": "0",
        "debouches": "Gestionnaire d’entreprises agricoles et agro-industrielles ;\nGestionnaire de coopératives et associations de producteurs ;\nConseiller en gestion d’entreprises agricoles et agroindustrielles ;\nAssistant planificateur du développement agricole ;\nEntrepreneur agricole ;\nEnseignant de collèges et lycées agricoles."
    },
    {
        "univ": "UNA",
        "ecole": "EAPA",
        "nom_complet": "Ecole d'Agrobusiness et de Politiques Agricoles",
        "nom": "Marketing des Intrants et Produits Agricoles (MIPA)",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/Toutes les options"],
        "matieres": [
            "Pour C, D: Maths, SPCT, SVT",
            "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."
        ],
        "bourses": "36",
        "aides": "0",
        "debouches": "Analyste du marché des produits et intrants agricoles ;\nMercaticien d’entreprises agricoles et agro-industrielles ;\nAgent commercial d’entreprise agricole et agro-industrielles ;\nEntrepreneur agricole ;\nEnseignant de collèges et lycées agricoles."
    },
    {
        "univ": "UNA",
        "ecole": "ESRVA",
        "nom_complet": "Ecole de Sociologie rurale et de Vulgarisation Agricole",
        "nom": "Sociologie rurale et Vulgarisation Agricole",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/toutes options"],
        "matieres": [
            "Pour C, D: Maths, SPCT, SVT",
            "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."
        ],
        "bourses": "43",
        "aides": "0",
        "debouches": "Technicien supérieur des entreprises agricoles ;\nTechnicien supérieur en Vulgarisateur/conseil agricole ;\nTechnicien de recherche dans les institutions de recherche nationales et internationales (sociologie rurale/vulgarisation) ;\nConseiller technique de cabinet de conseil agricole et vulgarisation ;\nConseiller technique de cabinet d’expertise agricole ;\nConseiller technique aux affaires techniques et financières des banques ;\nFonctionnaire d’Etat (ministères) ;\nFonctionnaire des collectivités décentralisées et faitières paysannes ;\nTechnicien spécialisé en gestion des organisations paysannes et syndicats paysans ;\nTechnicien spécialisé en gestion des parcs et aires protégées (populations riveraines) ;\nConseiller technique en nutrition humaine ;\nEnseignants des établissements et lycées agricoles ;\nTechnicien en gouvernance des filières et chaines de valeur agricole ;\nFonctionnaire des organisations de développement international (PNUD, Banque Mondiale, SNV, USAID etc)."
    },
    {
        "univ": "UNA",
        "ecole": "EForT",
        "nom_complet": "Ecole de Foresterie Tropicale",
        "nom": "Foresterie Tropicale",
        "mode": "Classement",
        "series": ["C", "D", "DEAT/Foresterie"],
        "matieres": [
            "Pour C, D: Maths, SPCT, SVT",
            "Pour DEAT: Prendre en compte toutes les trois (03) matières écrites."
        ],
        "bourses": "27",
        "aides": "0",
        "debouches": "Forestier Gestionnaire des ressources naturelles (Forêts, Eaux et Chasse) ;\nForestier Gestionnaire des réserves de faune et des aires protégées ;\nCartographe forestier ;\nSylviculteur (Planteur de bois d’œuvre, de service et énergie d'essences autochtones et exotiques) ;\nGestionnaire des Unités de productions sylvicoles ;\nOpérateur pilote de drones pour les collectes de données en forêt et traitement d'images ;\nEbéniste d'art et designer ;\nProducteur de biocharbon et dendroénergie ;\nSpécialiste de la domestication et élevage des gibiers ;\nSpécialiste des façonnages et transformations du bois ;\nProducteur des produits forestiers non ligneux (PFNL : miel, viande d'élevage non conventionnel, champignons) ;\nEnvironnementaliste ;\nChercheur des cabinets d’étude d’impact environnemental et de laboratoire de recherche ;\nEnseignant des lycées techniques agricoles ;\nFonctionnaire dans les Ministères (MCVDD, MAEP) et ONG."
    }
]