# Generated by Django 6.0.3 on 2026-04-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='etablissement',
            field=models.CharField(blank=True, max_length=150, verbose_name='Université ou École (pour les aînés)'),
        ),
        migrations.AddField(
            model_name='profil',
            name='type_utilisateur',
            field=models.CharField(choices=[('BACHELIER', "Nouveau Bachelier (En quête d'orientation)"), ('AINE', "Aîné / Étudiant (Partage d'expérience)")], default='BACHELIER', max_length=20, verbose_name='Qui êtes-vous ?'),
        ),
    ]
