# Generated by Django 6.0.5 on 2026-05-26 18:11

from django.db import migrations
from django.db.models import Q


def set_default_photos(apps, schema_editor):
    """Assigner la photo par défaut aux profils sans photo"""
    Profil = apps.get_model('comptes', 'Profil')
    
    # Trouver les profils sans photo (vides ou null)
    profils_sans_photo = Profil.objects.filter(
        Q(photo='') | Q(photo__isnull=True)
    )
    
    count = profils_sans_photo.count()
    
    # Mettre à jour tous les profils
    profils_sans_photo.update(photo='profils/default.png')
    
    print(f"\n✅ {count} profil(s) ont reçu la photo par défaut !")


def reverse_operation(apps, schema_editor):
    """Annuler l'opération si nécessaire"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_profil_etablissement_profil_type_utilisateur'),
    ]

    operations = [
        migrations.RunPython(set_default_photos, reverse_operation),
    ]
